name = "THICC-MC Modpack"
author = "TD"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5804d63bd2d56e1fd24dbfcab90f3bed3008cc46b35b2d65caf697f7a4e7fe0"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
