name = "THICC-MC Modpack"
author = "TD"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fc3b08f8cae299cdbac3b5c062726f30cecb7106fd1620ea5363fb88ed5fccb"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
