name = "THICC-MC Modpack"
author = "TD"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d87e19084ca95abd471090098c7d2aaa55e358cdbd77eb3d8d5f71be377713ec"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
