name = "THICC-MC Modpack"
author = "TD"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0f7a81640d31685fdc37b82cca7590de9e976910eb65745ef9d8c35a055334c"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
